"""create order_details 2.0

Revision ID: 21d305d3d57e
Revises: 430900fb0e72
Create Date: 2021-08-16 10:16:19.786638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d305d3d57e'
down_revision = '430900fb0e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='association_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='association_product_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name='association_pkey')
    )
    # ### end Alembic commands ###
